# -*- coding: utf-8 -*-
"""Linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11AFtU8k4DRlLsU4vPwvLZlP1ahNMMEep

# Building Your First Machine Learning Regression Model

# Importing the Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""# Importing the Dataset"""

# Importing the Dataset
sales_df = pd.read_csv("advertising_and_sales_.csv")

# Checking for the first 5 rows of the data
sales_df.head()

"""Preprocessing (X and y)
Code:



Explanation:
X (Features):
-------

This is the input (the "radio" column). It is a 2D matrix (even with one column) because models expect a matrix of inputs.

Explanation
y (Target):
-------

This is the output (the "sales" column). It is a 1D vector because it is just the answer we want.
"""

# Feature : radio column
X = sales_df["radio"].values
# Target: sales column
y = sales_df['sales'].values

print(X)

print(y)

"""# Reshaping X- So that scikit-learn sees it as a 2D"""

# Reshape X for scikit-learn (must be 2D)
X = X.reshape(-1, 1)
print("X shape:", X.shape)
print("y shape:", y.shape)

"""
# Importing the  Linear Regression Model
"""

# Import The Linear_Regression
from sklearn.linear_model import LinearRegression

# Creating the Model
model = LinearRegression()

# Fitting the Model
model.fit(X,y)

# Predict sales values
predictions = model.predict(X)
print(predictions[:5])

"""# Visualizing the Linear Regression Model"""

plt.figure(figsize=(8,6))

# Create scatter plot
plt.scatter(X, y, color="green")

# Create line plot
plt.plot(X, predictions, color="red")
plt.xlabel("Radio Expenditure ($)")
plt.ylabel("Sales ($)")

# Display the plot
plt.show()